// This file was auto-generated by ML.NET Model Builder. 

using System;
using MyMLAppML.Model;

namespace MyMLAppML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            
            Console.WriteLine("Donnez un commentaire: ");

            ModelInput input = new ModelInput()
            {
                Review = Console.ReadLine(),
            };
            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(input);

            Console.WriteLine($"\n\nPredicted Sentiment value {predictionResult.Prediction} \nPredicted Sentiment scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
